// <auto-generated />
using System;
using ClinicaFisioterapia.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClinicaFisioterapia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220720104641_Criando banco do zero")]
    partial class Criandobancodozero
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ClinicaFisioterapia.Models.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAgendamento")
                        .HasColumnType("datetime");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("IdFuncionario")
                        .IsUnique();

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("Agendamento");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Altura")
                        .HasColumnType("double");

                    b.Property<string>("AvaliacaoPostural")
                        .HasColumnType("text");

                    b.Property<bool>("Cirurgia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comobirdades")
                        .HasColumnType("text");

                    b.Property<string>("CondutaCurtoPrazo")
                        .HasColumnType("text");

                    b.Property<string>("CondutaLongoPrazo")
                        .HasColumnType("text");

                    b.Property<string>("CondutaMedioPrazo")
                        .HasColumnType("text");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("text");

                    b.Property<bool>("DormeBem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Fuma")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HMA")
                        .HasColumnType("text");

                    b.Property<bool>("HistoricoLesao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("HistoricoLesaoDescricao")
                        .HasColumnType("text");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<string>("MedicacaoEmUso")
                        .HasColumnType("text");

                    b.Property<string>("MedicacaoLesao")
                        .HasColumnType("text");

                    b.Property<int>("MembroDominante")
                        .HasColumnType("int");

                    b.Property<string>("MembrosAtivos")
                        .HasColumnType("text");

                    b.Property<string>("MembrosPassivos")
                        .HasColumnType("text");

                    b.Property<string>("ObservacaoAtividade")
                        .HasColumnType("text");

                    b.Property<string>("ObservacaoCirurgia")
                        .HasColumnType("text");

                    b.Property<string>("ObservacaoFuma")
                        .HasColumnType("text");

                    b.Property<string>("OutrasObservacoes")
                        .HasColumnType("text");

                    b.Property<double>("Peso")
                        .HasColumnType("double");

                    b.Property<bool>("PraticaAtividadeFisica")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TestesEspeciais")
                        .HasColumnType("text");

                    b.Property<string>("TestesFuncionais")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdMedico");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Evolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvolucao")
                        .HasColumnType("datetime");

                    b.Property<int>("IdSessao")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdSessao")
                        .IsUnique();

                    b.ToTable("Evolucao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarteiraConvenio")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Convenio")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int?>("EvolucaoId")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Profissao")
                        .HasColumnType("int");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<bool>("Situacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("EvolucaoId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameMedico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarteiraConvenio")
                        .HasColumnType("int");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Convenio")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EnderecoId")
                        .HasColumnType("int");

                    b.Property<int?>("EvolucaoId")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Profissao")
                        .HasColumnType("int");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.Property<bool>("Situacao")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EnderecoId")
                        .IsUnique();

                    b.HasIndex("EvolucaoId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Sessao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataSessao")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAvaliacao")
                        .HasColumnType("int");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAvaliacao");

                    b.HasIndex("IdFuncionario");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Sessao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Agendamento", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Funcionario", "Funcionario")
                        .WithOne("Agendamento")
                        .HasForeignKey("ClinicaFisioterapia.Models.Agendamento", "IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Paciente", "Paciente")
                        .WithOne("Agendamento")
                        .HasForeignKey("ClinicaFisioterapia.Models.Agendamento", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Avaliacao", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Funcionario", "Funcionario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Medico", "Medico")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Paciente", "Paciente")
                        .WithOne("Avaliacao")
                        .HasForeignKey("ClinicaFisioterapia.Models.Avaliacao", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Evolucao", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Sessao", "Sessao")
                        .WithOne("Evolucao")
                        .HasForeignKey("ClinicaFisioterapia.Models.Evolucao", "IdSessao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Funcionario", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Endereco", "Endereco")
                        .WithOne("Funcionario")
                        .HasForeignKey("ClinicaFisioterapia.Models.Funcionario", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Evolucao", "Evolucao")
                        .WithMany()
                        .HasForeignKey("EvolucaoId");

                    b.Navigation("Endereco");

                    b.Navigation("Evolucao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Paciente", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Endereco", "Endereco")
                        .WithOne("Paciente")
                        .HasForeignKey("ClinicaFisioterapia.Models.Paciente", "EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Evolucao", "Evolucao")
                        .WithMany()
                        .HasForeignKey("EvolucaoId");

                    b.Navigation("Endereco");

                    b.Navigation("Evolucao");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Sessao", b =>
                {
                    b.HasOne("ClinicaFisioterapia.Models.Avaliacao", "Avaliacao")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdAvaliacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Funcionario", "Funcionario")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaFisioterapia.Models.Paciente", "Paciente")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avaliacao");

                    b.Navigation("Funcionario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Avaliacao", b =>
                {
                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Endereco", b =>
                {
                    b.Navigation("Funcionario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Funcionario", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Medico", b =>
                {
                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Paciente", b =>
                {
                    b.Navigation("Agendamento");

                    b.Navigation("Avaliacao");

                    b.Navigation("Sessoes");
                });

            modelBuilder.Entity("ClinicaFisioterapia.Models.Sessao", b =>
                {
                    b.Navigation("Evolucao");
                });
#pragma warning restore 612, 618
        }
    }
}
